"""init schema

Revision ID: e6f6bede2651
Revises: 
Create Date: 2026-02-27 21:28:58.590053
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f6bede2651'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('external_user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_file_name', sa.String(), nullable=False),
    sa.Column('source_file_hash', sa.String(), nullable=True),
    sa.Column('imported_by', sa.String(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_billing_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=True),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contractor_pay_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_start_date', sa.Date(), nullable=True),
    sa.Column('effective_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('w9', 'insurance', 'contract', 'other', name='documenttype', native_enum=False), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('order_uid', sa.String(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('work_code', sa.String(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('client_name_raw', sa.String(), nullable=True),
    sa.Column('contractor_name_raw', sa.String(), nullable=True),
    sa.Column('contractor_user_id', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('inspector_due_date', sa.Date(), nullable=True),
    sa.Column('ecd_date', sa.Date(), nullable=True),
    sa.Column('window_start_date', sa.Date(), nullable=True),
    sa.Column('window_end_date', sa.Date(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_to_client_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_to_client_by', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('lender', sa.String(), nullable=True),
    sa.Column('loan_number', sa.String(), nullable=True),
    sa.Column('vacant', sa.Boolean(), nullable=True),
    sa.Column('photo_required', sa.Boolean(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('qc_user', sa.String(), nullable=True),
    sa.Column('mapping_address_1', sa.String(), nullable=True),
    sa.Column('mapping_address_2', sa.String(), nullable=True),
    sa.Column('mapping_city', sa.String(), nullable=True),
    sa.Column('mapping_state', sa.String(), nullable=True),
    sa.Column('mapping_zip', sa.String(), nullable=True),
    sa.Column('data_entry_error_code', sa.String(), nullable=True),
    sa.Column('client_pay_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contractor_pay_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paid_out_status', sa.Enum('unpaid', 'paid', name='paidoutstatus', native_enum=False), nullable=False),
    sa.Column('billed_status', sa.Enum('unbilled', 'billed', name='billedstatus', native_enum=False), nullable=False),
    sa.Column('missing_paid_out_rate', sa.Boolean(), nullable=False),
    sa.Column('conflicting_paid_out_rate', sa.Boolean(), nullable=False),
    sa.Column('missing_paid_in_rate', sa.Boolean(), nullable=False),
    sa.Column('conflicting_paid_in_rate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_client_name_raw_order_number', 'orders', ['client_name_raw', 'order_number'], unique=False)
    op.create_index('ix_orders_order_uid', 'orders', ['order_uid'], unique=True)
    op.create_table('payroll_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_name', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'paid', 'void', name='payrollbatchstatus', native_enum=False), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_batch_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_batch_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('pay_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_out_status', sa.Enum('unpaid', 'paid', name='paidoutstatus', native_enum=False), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payroll_batch_id'], ['payroll_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_batch_items')
    op.drop_table('payroll_batches')
    op.drop_index('ix_orders_order_uid', table_name='orders')
    op.drop_index('ix_orders_client_name_raw_order_number', table_name='orders')
    op.drop_table('orders')
    op.drop_table('documents')
    op.drop_table('contractor_pay_rates')
    op.drop_table('client_billing_rates')
    op.drop_table('import_batches')
    op.drop_table('contractors')
    op.drop_table('clients')
    # ### end Alembic commands ###
